### ISSUE TITLE
转发消息报错

### ISSUE THREAD

**Issue by LinBoyan** [icqqjs/icqq#104]
在0.4.12中原有的制作转发消息开始报错

![image](https://github.com/icqqjs/icqq/assets/69086800/24bc21bb-e140-42f6-a15c-781ab36445ea)

这是报错部分的代码
![image](https://github.com/icqqjs/icqq/assets/69086800/893aeec2-a81c-4442-afe2-938553d3778a)

**Comment by xfdown** [comment]
新版本改成了json格式，适配例子： 
if (typeof (forwardMsg.data) === 'object') {
      let detail = forwardMsg.data?.meta?.detail
      if (detail) {
        detail.news = [{ text: dec }]
      }
    } else {
      forwardMsg.data = forwardMsg.data
        .replace(/\n/g, '')
        .replace(/<title color="#777777" size="26">(.+?)<\/title>/g, '___')
        .replace(/___+/, `<title color="#777777" size="26">${dec}</title>`)
    }
