### ISSUE TITLE
ios端图片缩放小

### ISSUE THREAD

**Issue by YouYouLip** [icqqjs/icqq#106]
### Node.js Version

Node.js v16.17.0.

### Package(icqq) Version

0.4.12

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

有没有一种可能，ios端群聊图片为表情这个问题是修复了，但是缩放这个没有（雾），以下是ios端看到的，ios版本是16.6（20G75），QQ版本v8.9.70.636，虽说在主界面看群聊消息显示的是图片，但是可以发现右上角有给4个方块的选项，那个是图片格式没有的，会不会是伪图片格式？（雾）反正我只知道我ios看群聊的图特别小，缩放小，私聊是正常比例，安卓不管是群聊还是私聊都没事
![43W8BH QRBGY(WK }NK{FK](https://github.com/icqqjs/icqq/assets/119958263/891c3bfe-c4bd-4862-96c2-4a291552d63c)

**Comment by YouYouLip** [comment]
gocq之前也是1.0.1版本是ios私聊看不见图片 群聊能看见，1.1.0修好了，但是，是我的问题还是（雾）

**Comment by JadeVane** [comment]
我也遇到这个问题，还以为是设置错误

使用的是 Tim，部署了api，版本 8.9.68

安卓和电脑都正常，只有IOS报错

**Comment by YouYouLip** [comment]
> 我也遇到这个问题，还以为是设置错误
> 
> 使用的是 Tim，部署了api，版本 8.9.68
> 
> 安卓和电脑都正常，只有IOS报错

实在不行 就只能转gocq了，因为我这边是绑一个终端当启动器编写在云崽里了 直接把icqq和云崽在一个命令行里一起启动，转gocq的话我还要重新部署了（气） 结果icqq上写着修复了 我进去也看了 代码确实有变动结果还是没用

**Comment by YouYouLip** [comment]
> 我也遇到这个问题，还以为是设置错误
> 
> 使用的是 Tim，部署了api，版本 8.9.68
> 
> 安卓和电脑都正常，只有IOS报错

要么继续等修复，要么只能换gocq协议了，不过 云崽绝大部分用的都是icqq，应该没得换

**Comment by Oishiimono** [comment]
搬运一个手动解决办法

文件位置：Miao-Yunzai\node_modules\.pnpm\icqq@0.4.12\node_modules\icqq\lib\message
目标文件：image.js

修改内容：（第226行修改为）2: this.md5.toString("hex") + (this.asface?".gif":".jpg"),

**Comment by JadeVane** [comment]
> 搬运一个手动解决办法
> 
> 文件位置：Miao-Yunzai\node_modules.pnpm\icqq@0.4.12\node_modules\icqq\lib\message 目标文件：image.js
> 
> 待修改内容：（第226行）2: this.md5.toString("hex") +".gif" 手动改为：2: this.md5.toString("hex") + (this.asface?".gif":".jpg"),

解决了！原因是生成了动图，然后发送的时候被当成表情了？

**Comment by xfdown** [comment]
有没有一种可能，我修复了但没build，看你们聊了好几天，结果你们就是不知道看看提交了什么。。。
