### ISSUE TITLE
自动选择签名API支持的协议版本功能未生效

### ISSUE THREAD

**Issue by BennettChina** [icqqjs/icqq#125]
### Node.js Version

16.20.0

### Package(icqq) Version

0.5.2

### Login Protocol

aPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

未在config中指定版本时，自动使用签名Api支持的协议版本，但实际上并未生效，我debug时发现没有走到[此函数](https://github.com/icqqjs/icqq/blob/99973be2ea70a26e12bc01d0e997473780157d14/src/core/qsign.ts#L235C54-L235C54)内。

<img width="673" alt="image" src="https://github.com/icqqjs/icqq/assets/48208644/54c3ad94-0185-4f1c-b43a-08c532d9a995">
<img width="592" alt="image" src="https://github.com/icqqjs/icqq/assets/48208644/0c63805b-8927-43ae-aa0c-595c50cd5739">

### Log Details (控制台日志，请提供包含前后一段时间内的)

<img width="685" alt="image" src="https://github.com/icqqjs/icqq/assets/48208644/c599d168-27cd-496f-b888-964ef4f4cf17">

**Comment by xfdown** [comment]
是否调用了login函数进行登录？

**Comment by BennettChina** [comment]
调用了的，最后是以日志打印中的协议版本号登录上的。

**Comment by xfdown** [comment]
sign正常返回吗
？

**Comment by BennettChina** [comment]
是正常的，有打印[qsign]getSign MessageSvc.PbSendMsg result(2408ms)这条日志，code也是0。奇怪的是刚才我又启动一次发现触发了getApiQQVer函数，而此时日志打印是这样的：

```
[15:37:57.032] [icqq] [INFO] - [undefined]获取到签名Api协议版本：8.9.63
[15:37:57.033] [icqq] [INFO] - [***********]使用协议：aPad_8.9.63.11390
```

在此之前我的操作是不填ver(未触发)，填ver=8.9.63（未触发），不填ver（触发），有的奇怪。

**Comment by BennettChina** [comment]
最后这次好像是token过期重新获取签名token时触发的，启动时的第一条仍然是[***********]使用协议：aPad_8.9.76.12115

**Comment by xfdown** [comment]
感觉像是你第一次login的时候没完全初始化的问题。

**Comment by xfdown** [comment]
你试试在创建client之后延迟一会再调用login看看

**Comment by BennettChina** [comment]
好像并不行，我打了个debug等了一分多钟。我创建client是在构造器中执行的，login是它类中的方法，在login前client应该是初始化完的。

**Comment by xfdown** [comment]
你试试刚提交的这个

**Comment by xfdown** [comment]
dev分支

**Comment by BennettChina** [comment]
好的，等我回到家后再试试。

**Comment by BennettChina** [comment]
可以了，`0.5.3` 已经修复掉了。
