### ISSUE TITLE
签名api(energy)异常： 810_9 result(8ms): {"code":-1,"msg":"Request failed with status code 405"}

### ISSUE THREAD

**Issue by linonetwo** [icqqjs/icqq#130]
### Node.js Version

v20.2.0

### Package(icqq) Version

0.5.4

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

在 icqq 里打 log 发现尝试 POST，energy 不能 post

POST http://localhost:13579/energy {
ver: '8.9.80',
uin: 128768,
data: '810_9',
guid: '6379d5b4ab7eddfff',
version: '6.0.0.2554'
}

https://github.com/fuqiuluo/unidbg-fetch-qsign#%E7%99%BB%E5%BD%95%E5%8C%85energytlv544

```
        url.pathname = path;
        // DEBUG: console post_params
        console.log(`post_params`, url.href, post_params);
        const { data } = await axios_1.default.post(url.href, post_params, {
            timeout: 15000,
            headers: {
                'User-Agent': `icqq@${this.pkg.version} (Released on ${this.pkg.upday})`,
                'Content-Type': "application/x-www-form-urlencoded"
            }
        }).catch(err => ({ data: { code: -1, msg: err?.message } }));
        this.emit("internal.verbose", `getT544 ${cmd} result(${Date.now() - time}ms): ${JSON.stringify(data)}`, base_client_1.VerboseLevel.Debug);
```

### Log Details (控制台日志，请提供包含前后一段时间内的)

[2023-09-24T23:22:30.673] [INFO] [icqq] - [1287688945]使用协议：Android_8.9.80.12440
post_params http://localhost:13579/energy {
  ver: '8.9.80',
  uin: 1287,
  data: '810_9',
  guid: '6379d5b4ab7ed',
  version: '6.0.0.2554'
}
[2023-09-24T23:22:30.906] [ERROR] [icqq] - 签名api(energy)异常： 810_9 result(4ms): {"code":-1,"msg":"Request failed with status code 405"}
[2023-09-24T23:22:31.348] [MARK] [icqq] - 112.86.231.155:8080 connected
[2023-09-24T23:22:31.484] [MARK] [icqq] - 收到滑动验证码，请访问以下地址完

**Comment by linonetwo** [comment]
手动改为 get 请求后可以登录

···
        const { data } = await axios_1.default.get(url.href, {
            params: post_params,
            timeout: 30000,
            headers: {
                'User-Agent': `icqq@${this.pkg.version} (Released on ${this.pkg.upday})`,
                'Content-Type': "application/x-www-form-urlencoded"
            }
        }).catch(err => ({ data: { code: -1, msg: err?.message } }));
···

**Comment by xfdown** [comment]
你在api后面加上?key=xxx才支持qsign

**Comment by linonetwo** [comment]
sign_api_addr: http://localhost:13579/sign?key=1145141919810   这样对吧

现在报 [登陆失败](237)当前QQ登录频繁，暂时被限制登录，建议更换QQ或稍后再尝试登录！ 了，我明天再试试
