### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by wEuphorIA** [icqqjs/icqq#137]
### Package(icqq) Version

icqq@0.5.3

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

[MiaoYz][22:08:15.454][MARK] Miao-Yunzai 启动中...
[MiaoYz][22:08:15.461][INFO] 正在连接 redis://127.0.0.1:6379/0
[MiaoYz][22:08:15.470][INFO] Redis 连接成功
[MiaoYz][22:08:15.500][MARK] ----------
[MiaoYz][22:08:15.501][MARK] Package Version: icqq@0.5.3 (Released on 2023/9/1)
[MiaoYz][22:08:15.501][MARK] View Changelogs：https://github.com/icqqjs/icqq/rel
eases
[MiaoYz][22:08:15.501][MARK] ----------
[MiaoYz][22:08:16.376][INFO] [Chromium] C:/Program Files/Google/Chrome/Applicati
on/chrome.exe
[MiaoYz][22:08:16.377][INFO] 加载渲染后端 puppeteer
[MiaoYz][22:08:16.403][INFO] [3649488947]获取到签名Api协议版本：8.9.68
[MiaoYz][22:08:16.403][INFO] [3649488947]使用协议：aPad_8.9.68.11565
[MiaoYz][22:08:17.481][MARK] 14.22.9.84:8080 connected
[MiaoYz][22:08:17.658][MARK] 收到滑动验证码，请访问以下地址完成滑动，并从网络响
应中取出ticket输入：https://ssl.captcha.qq.com/template/wireless_mqq_captcha.htm
l?style=simple&aid=16&uin=3649488947&sid=4792107309782793682&cap_cd=RigAPyH5btb0
yCglHe5E9lUM0UMpIA-RtFgxcbbnEg7S0kLbxC8MIg**&clientype=1&apptype=2

------------------↓↓滑动验证链接↓↓----------------------

https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=1
6&uin=3649488947&sid=4792107309782793682&cap_cd=RigAPyH5btb0yCglHe5E9lUM0UMpIA-R
tFgxcbbnEg7S0kLbxC8MIg**&clientype=1&apptype=2

--------------------------------------------------------
提示：打开上面链接获取ticket，可使用【滑动验证app】获取
链接存在有效期，请尽快操作，多次操作失败可能会被冻结
滑动验证app下载地址：https://wwp.lanzouy.com/i6w3J08um92h 密码:3kuu

? 触发滑动验证，需要获取ticket通过验证，请选择获取方式: 0.自动获取ticket

----请打开下方链接并在2分钟内进行验证----
https://hlhs-nb.cn/captcha/slider?key=3649488947
----完成后将自动进行登录----
[MiaoYz][22:08:34.537][WARN] token失效: [禁止登录]你当前使用的QQ版本过低，请前往
QQ官网im.qq.com下载最新版QQ后重试。(错误码：45)
[MiaoYz][22:08:34.537][ERRO] [禁止登录]你当前使用的QQ版本过低，请前往QQ官网im.qq
.com下载最新版QQ后重试。
[MiaoYz][22:08:34.538][ERRO] 登录错误，已停止运行

**Comment by wEuphorIA** [comment]
而且切换其他账号能正常登录。这是为什么

**Comment by wEuphorIA** [comment]
谢谢

**Comment by YouYouLip** [comment]
我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行

**Comment by Strawxiguan** [comment]
隔壁gocq已经发出了停止维护的消息https://github.com/Mrs4s/go-cqhttp/issues/2471

**Comment by Strawxiguan** [comment]
很有可能协议登录会成为历史（个人推测，不代表真实性）

**Comment by wEuphorIA** [comment]
> 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行



> 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行



> 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行

我也是这样

**Comment by wEuphorIA** [comment]
> 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行

我也是这样

**Comment by wEuphorIA** [comment]
> 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行

https://github.com/CikeyQi/QQsign_docs/blob/main/index.mdkeyi可以试试这个，用了这个好了

**Comment by YouYouLip** [comment]
> > 我也是出现了这个问题 目前只能用手表协议，8.9.63，8.9.68，8.9.71，8.9.73版本api 安卓手机还是安卓平板以及icqq0.4.12和0.5.3能试的都试了 均是code45 挂了3个q 有2个q号被封了45 之前一直没有过 昨天突然就出45了 离谱的是怎么换协议换api都不行
> 
> https://github.com/CikeyQi/QQsign_docs/blob/main/index.md 可以试试这个，我用了这个好了，应该是签名服务太老的问题

我也是，我去你那边看了一眼，这个只是qsign空间而已，但是我发现了个8.9.80的签名，因为目前8.9.78说是加了随机类检测，api跳过不了这样的，但是qsign的1.1.9支持，我寻思我去看了一眼然后把里面那个人的文件下了copy到服务器那边用icqq0.5.4和8.9.80版本进行签名 没想到居然可以活了

我是在这下的https://huggingface.co/spaces/CikeyQI/QQsign/tree/main/txlib/8.9.80
