### ISSUE TITLE
[安全提醒]当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。

### ISSUE THREAD

**Issue by Nedfre** [icqqjs/icqq#19]
### Node.js Version

14.10.0

### Package(icqq) Version

0.2.3

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![Uploading ZCKQ`CR7G@ZRNR1BN3RVUMR.png…]()

### Log Details (控制台日志，请提供包含前后一段时间内的)

![Uploading ZCKQ`CR7G@ZRNR1BN3RVUMR.png…]()

**Comment by dondaha** [comment]
```
[MiaoYz][00:32:48.322][WARN] token失效: [禁止登录]你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。(错误码：45)
[MiaoYz][00:32:48.323][ERRO] [禁止登录]你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。
[MiaoYz][00:32:48.323][ERRO] 登录错误，已停止运行
```
Today I can't login too
