### ISSUE TITLE
版本过低235

### ISSUE THREAD

**Issue by fatebugs** [icqqjs/icqq#23]
### Node.js Version

v16.19.1

### Package(icqq) Version

0.3.1

### Login Protocol

None

### Log Details (控制台日志，请提供包含前后一段时间内的)

![image](https://user-images.githubusercontent.com/65278566/234828862-741c73c0-dd1b-4813-8887-7c762fb98e0f.png)

**Comment by ZhangGoose** [comment]
同蹲解决办法

**Comment by Niloux3d** [comment]
同错误码45

**Comment by Ghost-chu** [comment]
我也是错误码45

**Comment by kanzakine** [comment]
蚌埠住了 我也45

**Comment by Ghost-chu** [comment]
我解决了，更新Yunzai之后，删除device.json，把QQ设备锁打开，然后走一遍短信验证码登录就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月4日(周四) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [icqqjs/icqq] 版本过低235 (Issue #23)




 
蚌埠住了 我也45

**Comment by fatebugs** [comment]
我清空了一次data，然后重新pnpm了一下就能跑了，npm的貌似不行，暂时不清楚为什么，我用的node版本是16

**Comment by Kurehava** [comment]
> > 淦，我今晚是错误码45，Mac的登录方式也不好使了，是qq更新协议了么
> 
> platform:6 试过吗？

我platform 6昨天行，今天也不行了

**Comment by ywstratus** [comment]
> > 淦，我今晚是错误码45，Mac的登录方式也不好使了，是qq更新协议了么
> 
> platform:6 试过吗？

我这边好了，我今天是把所有依赖删了重新下，所有缓存删干净，全部流程从头走一遍。

**Comment by 1294266616** [comment]
> 235删掉设备信息重新生成就好了（device.json）

尝试成功登录上去了

**Comment by lc-cn** [comment]
最新版icqq需要配置签名API使用，自建签名服务参考这个[comment](https://github.com/icqqjs/icqq/issues/65#issuecomment-1619573088))
