### ISSUE TITLE
如何管理client的事件监听器

### ISSUE THREAD

**Issue by Vi-brance** [icqqjs/icqq#24]
从`oicq`的 [issue](https://github.com/takayama-lily/oicq/issues/519) 过来的，@lc-cn 请问`TripTrap`有没有与`EventEmitter`一样的管理监听器的功能？我翻看源码的时候发现您在修改时将emitter管理监听器的函数删除了，但是似乎没有添加一个相同功能的函数？

**Comment by lc-cn** [comment]
const dispose=client.on('system.online',callback)
dispose()

**Comment by Vi-brance** [comment]
非常感谢，我还不太了解`dispose`的运作原理，献丑了
