### ISSUE TITLE
token失效

### ISSUE THREAD

**Issue by fatebugs** [icqqjs/icqq#26]
### Node.js Version

v16.19.1

### Package(icqq) Version

0.3.2

### Login Protocol

None

### Log Details (控制台日志，请提供包含前后一段时间内的)

![image](https://user-images.githubusercontent.com/65278566/236449262-8a752ab9-46b3-4383-b58a-ccf34b98a4c1.png)

**Comment by fatebugs** [comment]
尝试次数过多现在貌似风控了

**Comment by lc-cn** [comment]
最新版已修
