### ISSUE TITLE
Yunzai更新icqq至0.3.2后出现问题

### ISSUE THREAD

**Issue by lanxiaoze** [icqqjs/icqq#27]
错误详情：
023-05-06 15:43:02.233469724] 正在启动：Yunzai
[YzBot][15:43:16.675][MARK] Yunzai-Bot 启动中...
[YzBot][15:43:16.683][MARK] 连接redis.... [YzBot][15:43:16.747][MARK] 连接redis成功 [YzBot][15:43:16.810][MARK] ---------- [YzBot][15:43:16.811][MARK] Package Version: icqq@0.3.2 (Released on 2023/4/29) [YzBot][15:43:16.811][MARK] View Changelogs：[https://github.com/icqqjs/icqq/releases](https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Ficqqjs%2Ficqq%2Freleases) [YzBot][15:43:16.813][MARK] ---------- [YzBot][15:43:18.837][INFO] Calculating PoW of plus 10000 times cost 332 ms node:internal/crypto/cipher:122 this[kHandle].initiv(cipher, credential, iv, authTagLength); ^ Error: error:0308010C:digital envelope routines::unsupported at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19) at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3) at new Cipheriv (node:internal/crypto/cipher:249:3) at Object.createCipheriv (node:crypto:148:10) at sign (/root/TRSS_AllBot/Yunzai/node_modules/.pnpm/icqq@0.3.2/node_modules/icqq/lib/internal/enctyption.js:465:27) at 1348 (/root/TRSS_AllBot/Yunzai/node_modules/.pnpm/icqq@0.3.2/node_modules/icqq/lib/core/tlv.js:400:72) at Yunzai.packTlv (/root/TRSS_AllBot/Yunzai/node_modules/.pnpm/icqq@0.3.2/node_modules/icqq/lib/core/tlv.js:37:24) at Yunzai.passwordLogin (/root/TRSS_AllBot/Yunzai/node_modules/.pnpm/icqq@0.3.2/node_modules/icqq/lib/core/base-client.js:382:31) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Yunzai.login (/root/TRSS_AllBot/Yunzai/node_modules/.pnpm/icqq@0.3.2/node_modules/icqq/lib/client.js:210:24) {
library: 'digital envelope routines',
reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v19.9.0 [2023-05-06 15:43:18.924086909] 进程停止了，12秒后尝试重启

**Comment by meng-fucius** [comment]
+1 同样的问题

**Comment by touchscale** [comment]
+1

**Comment by touchscale** [comment]
建议先pnpm uninstall icqq，然后pnpm install icqq@0.3.1 -w,降回0.3.1
