### ISSUE TITLE
icqq登陆token失效

### ISSUE THREAD

**Issue by TakeNAKE** [icqqjs/icqq#29]
### Node.js Version

18.16.0

### Package(icqq) Version

0.3.2

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

总是获取token失效，之后就是报错237

### Log Details (控制台日志，请提供包含前后一段时间内的)

![Screenshot_20230509_075537_com termux](https://user-images.githubusercontent.com/105784549/236961244-0eba5ff0-7d0b-45e9-81e5-215315587148.jpg)

**Comment by TakeNAKE** [comment]
群友们也都在反馈这个问题

**Comment by Ghost-chu** [comment]
我也是相同错误

**Comment by 43887016** [comment]
类似错误，日志如下

[MiaoYz][09:37:11.576][MARK] Package Version: icqq@0.3.2 (Released on 2023/4/29)
[MiaoYz][09:37:11.580][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[MiaoYz][09:37:11.582][MARK] ----------
[MiaoYz][09:37:12.989][MARK] [渲染后端加载]: 导入 puppeteer
[MiaoYz][09:37:13.783][INFO] Calculating PoW of plus 10000 times cost 272 ms
[MiaoYz][09:37:13.876][MARK] 106.55.127.172:8080 connected
[MiaoYz][09:37:13.980][MARK] 登录token过期
[MiaoYz][09:37:13.982][MARK] 3秒后重新连接
[MiaoYz][09:37:17.216][INFO] Calculating PoW of plus 10000 times cost 220 ms
[MiaoYz][09:37:17.333][MARK] 登录token过期
[MiaoYz][09:37:17.334][MARK] 3秒后重新连接
[MiaoYz][09:37:20.589][INFO] Calculating PoW of plus 10000 times cost 242 ms
[MiaoYz][09:37:20.697][MARK] 登录token过期
[MiaoYz][09:37:20.698][MARK] 3秒后重新连接
[MiaoYz][09:37:23.892][INFO] Calculating PoW of plus 10000 times cost 179 ms
[MiaoYz][09:37:24.001][WARN] token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[MiaoYz][09:37:24.002][ERRO] [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
[MiaoYz][09:37:24.007][ERRO] 登录错误，已停止运行

**Comment by Timor-wu** [comment]
我也是 错误码237

**Comment by meng-fucius** [comment]
有解决方案了吗

**Comment by Ghost-chu** [comment]
我也是237

**Comment by dmlgzs** [comment]
v0.3.3已修复
