### ISSUE TITLE
token失效: [禁止登录]登录失败，建议升级最新版本后重试

### ISSUE THREAD

**Issue by Arondight** [icqqjs/icqq#30]
### Node.js Version

v18.14.2

### Package(icqq) Version

0.3.2

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

如题，密码登录

### Log Details (控制台日志，请提供包含前后一段时间内的)

```
[2023-05-09T10:45:35.347] [INFO] [icqq] - Calculating PoW of plus 10000 times cost 98 ms
[2023-05-09T10:45:35.352] [DEBUG] [icqq] - send:wtlogin.login seq:3665
[2023-05-09T10:45:35.427] [MARK] [icqq] - 120.232.130.13:8080 connected
[2023-05-09T10:45:35.428] [DEBUG] [icqq] - send:Client.CorrectTime seq:3666
[2023-05-09T10:45:35.477] [DEBUG] [icqq] - recv:Client.CorrectTime seq:3666
[2023-05-09T10:45:35.598] [DEBUG] [icqq] - recv:wtlogin.login seq:3665
[2023-05-09T10:45:35.599] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[2023-05-09T10:45:35.600] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
```

**Comment by buzuosheng** [comment]
我想多加个插件，结果就登不上去了。。。就不该有这样的想法。。

**Comment by wuhen007** [comment]
https://hanxuan.cc/docs/token.html   临时解决token失效

**Comment by lc-cn** [comment]
最新版已修

**Comment by Arondight** [comment]
最新版仍未修复

**Comment by gaqwe767** [comment]
ICQQ@0.3.10还是会报(错误码：45)，安卓手Q协议

**Comment by lc-cn** [comment]
> ICQQ@0.3.10还是会报(错误码：45)，安卓手Q协议

尝试使用协议6

**Comment by Msdyz123** [comment]
同样也出现了错误码45禁止登录，之前一次更新看日志可以pnpm升级依赖，结果升级之后icqq0.3.10版本出现了这个问题，同时机器人的QQ号无法登录电脑版QQ，手机QQ没影响，电脑QQ其他账号都能正常登录并且是最新版本，但是登录机器人的账号就显示版本低去官网下最新版，不知道有没有关系，目前降级icqq尝试中，还是没能登上

**Comment by MskTmi** [comment]
我也是错误码45，下面是个人解决方案 可以参考一下
- `pnpm update`  更新依赖
- 删除device.json
- 更换ipad协议

**Comment by gaqwe767** [comment]
> > ICQQ@0.3.10还是会报(错误码：45)，安卓手Q协议
> 
> 尝试使用协议6
协议6也登不上（一样的错误45），但是手表协议登上了...

**Comment by Syne-lucky** [comment]
我也是code45，以下处理办法2023/06/08可用：
pnpm update icqq 更新icqq到最新的
删掉data文件夹里面的device.json
npm run login
选择协议old Android

**Comment by Arondight** [comment]
> 尝试使用协议6

协议6仍无法登录

**Comment by Strawxiguan** [comment]
8.88也开始概率45了

**Comment by bailiyang** [comment]
> 

> yunzai@3.0.0 login
> node app.js login

欢迎使用Yunzai-Bot v3.0.0
请按提示输入完成QQ配置
? 请输入机器人QQ号(请用小号)： xxxxxxxx
? 请输入登录密码(为空则扫码登录)： [hidden]
? 请选择登录端口： iPad

QQ配置完成，正在登录
后续修改账号可以运行命令： npm run login

[YzBot][11:22:39.189][MARK] Yunzai-Bot 启动中...
[YzBot][11:22:39.190][MARK] 连接redis....
[YzBot][11:22:39.196][MARK] 连接redis成功
[YzBot][11:22:39.202][WARN] 未配置签名API地址，登录/消息发送可能失败
[YzBot][11:22:39.203][MARK] ----------
[YzBot][11:22:39.203][MARK] Package Version: icqq@0.4.7 (Released on 2023/6/25)
[YzBot][11:22:39.203][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[YzBot][11:22:39.203][MARK] ----------
[YzBot][11:22:39.239][INFO] [443412293]使用协议：iPad_8.9.50.10650
[YzBot][11:22:39.489][MARK] 123.125.0.161:8080 connected
[YzBot][11:22:39.755][WARN] token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[YzBot][11:22:39.756][ERRO] [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
[YzBot][11:22:39.756][ERRO] 登录错误，已停止运行

6月28日，该方法失效

**Comment by Syne-lucky** [comment]
> 我也是code45，以下处理办法2023/06/08可用： pnpm update icqq 更新icqq到最新的 删掉data文件夹里面的device.json npm run login 选择协议old Android

后续：被连着冻结了两次，呜呜呜

**Comment by bailiyang** [comment]
> yunzai@3.0.0 login
> node app.js login

欢迎使用Yunzai-Bot v3.0.0
请按提示输入完成QQ配置
? 请输入机器人QQ号(请用小号)： xxxxxxxxx
? 请输入登录密码(为空则扫码登录)： [hidden]
? 请选择登录端口： 安卓手表

QQ配置完成，正在登录
后续修改账号可以运行命令： npm run login

[YzBot][11:33:49.044][MARK] Yunzai-Bot 启动中...
[YzBot][11:33:49.044][MARK] 连接redis....
[YzBot][11:33:49.051][MARK] 连接redis成功
[YzBot][11:33:49.057][WARN] 未配置签名API地址，登录/消息发送可能失败
[YzBot][11:33:49.057][MARK] ----------
[YzBot][11:33:49.057][MARK] Package Version: icqq@0.4.8 (Released on 2023/7/1)
[YzBot][11:33:49.057][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[YzBot][11:33:49.057][MARK] ----------
[YzBot][11:33:49.093][INFO] [xxxxxxxx]使用协议：Watch_2.0.8
[YzBot][11:33:49.093][WARN] 手表协议不支持密码登入，将使用扫码登入
[YzBot][11:33:49.113][MARK] 119.147.190.138:8080 connected

7月3日升级0.4.8后，选手表登录成功，没有封禁token，其他方式则不行

**Comment by Strawxiguan** [comment]
> > yunzai@3.0.0 login
> > node app.js login
> 
> 欢迎使用Yunzai-Bot v3.0.0 请按提示输入完成QQ配置 ? 请输入机器人QQ号(请用小号)： xxxxxxxxx ? 请输入登录密码(为空则扫码登录)： [hidden] ? 请选择登录端口： 安卓手表
> 
> QQ配置完成，正在登录 后续修改账号可以运行命令： npm run login
> 
> [YzBot][11:33:49.044][MARK] Yunzai-Bot 启动中... [YzBot][11:33:49.044][MARK] 连接redis.... [YzBot][11:33:49.051][MARK] 连接redis成功 [YzBot][11:33:49.057][WARN] 未配置签名API地址，登录/消息发送可能失败 [YzBot][11:33:49.057][MARK] ---------- [YzBot][11:33:49.057][MARK] Package Version: icqq@0.4.8 (Released on 2023/7/1) [YzBot][11:33:49.057][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases [YzBot][11:33:49.057][MARK] ---------- [YzBot][11:33:49.093][INFO] [xxxxxxxx]使用协议：Watch_2.0.8 [YzBot][11:33:49.093][WARN] 手表协议不支持密码登入，将使用扫码登入 [YzBot][11:33:49.113][MARK] 119.147.190.138:8080 connected
> 
> 7月3日升级0.4.8后，选手表登录成功，没有封禁token，其他方式则不行

手表可以登录，但是消息会-70风控。

**Comment by lc-cn** [comment]
最新版icqq需要签名才能继续登录，自建签名参考这个[comment](comment)
