### ISSUE TITLE
关于watch和apad协议的一个问题

### ISSUE THREAD

**Issue by Vi-brance** [icqqjs/icqq#41]
在oicq的 [wiki](https://github.com/takayama-lily/oicq/wiki/02.%E5%85%B6%E4%BB%96%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 中写到`watch`和`apad`协议缺少部分功能。
- 请问在这个项目中是否已经修复了？
- 如果没有请问有没有修复的打算？

**Comment by lc-cn** [comment]
未修复，暂无修复计划
