### ISSUE TITLE
API文档更新

### ISSUE THREAD

**Issue by Vi-brance** [icqqjs/icqq#42]
我在参考这个模块的API文档时发现绝大部分内容还是搬运自oicq的原API文档，相关API的代码链接也是原作者的commit的对应代码，在仓库搜索时部分API已经被修改或扩充，希望大佬能考虑更新一下API文档。

在此提前感谢大佬的开发成果！

**Comment by Vi-brance** [comment]
作者你好，许久没收到您的回复，我将尝试自己补充代码注释，希望能得到您的批准。

**Comment by lc-cn** [comment]
谔谔，API文档同步更了的

**Comment by Vi-brance** [comment]
> 谔谔，API文档同步更了的

不好意思，我的意思是有一些代码并没有比较完整的注释，希望能够有一个比较清晰的说明

**Comment by lc-cn** [comment]
> > 谔谔，API文档同步更了的
> 
> 不好意思，我的意思是有一些代码并没有比较完整的注释，希望能够有一个比较清晰的说明

抱歉，我无法确定你指的一些代码是哪些，如果有必要，你可以补充代码注释后提交Pull Request
