### ISSUE TITLE
token失效: [登录失败]请你稍后重试。

### ISSUE THREAD

**Issue by bling-yshs** [icqqjs/icqq#50]
### Node.js Version

16.17.0

### Package(icqq) Version

latest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

看起来是安卓8.8.88也不行了(device.json已经删除过)（是别人的问题然后来问我，所以我本人可能没法复现）

[YzBot][12:55:22.176][MARK] 收到登录保护，只需验证一次便长期有效，可以访问URL验证或发短信验证。访问URL完成验证后调用login()可直接登录。发短信验证需要调用sendSmsCode()和submitSmsCode()方法。
[YzBot][12:55:22.177][MARK] 登录保护验证URL：https://accounts.qq.com/safe/qrcode?_wv=2&_wwv=128&envfrom=double-check&uin=255516491&sig=tAMpwtWSzeRThxBUW1hnVRIxpUFwYfEzMuf4peZKUlrYVNYS4dAMvrReQl6clEEsdjOL0HbEAahgj5F5h8usy3UJAbVbCLdfS7Y39igF1%2Fk%3D
[YzBot][12:55:22.177][MARK] 密保手机号：

------------------↓↓设备锁验证↓↓----------------------

? 触发设备锁验证，请选择验证方式: 2.发送短信验证码到密保手机

[YzBot][12:55:26.485][WARN] token失效: [登录失败]请你稍后重试。(0x88)(错误码：136)
[YzBot][12:55:26.485][ERRO] [登录失败]请你稍后重试。(0x88)
[YzBot][12:55:26.486][ERRO] 登录错误，已停止运行

**Comment by vikiboss** [comment]
啊嘞

**Comment by lc-cn** [comment]
缩圈了，不予解决
