### ISSUE TITLE
旧版token于当前版本不兼容

### ISSUE THREAD

**Issue by caojinlin** [icqqjs/icqq#51]
### Node.js Version

v14.16.1

### Package(icqq) Version

^0.3.14

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://github.com/icqqjs/icqq/assets/20088097/7d13da39-a826-474d-83e5-6f3583602661)

**Comment by Stapxs** [comment]
新版本更新的有一部分原因就是 token 换了 emmm
所以删掉旧版 token 重新登录吧 ……

**Comment by BennettChina** [comment]
新版好像需要v16多node,所以...

**Comment by AmamiHaruka** [comment]
@Stapxs 旧版token的目录是存在哪里，data目录下似乎没有找到

**Comment by Stapxs** [comment]
> @Stapxs 旧版token的目录是存在哪里，data目录下似乎没有找到

~/.oicq 下面
