### ISSUE TITLE
最新版本的ICQQ也出现了45错误码

### ISSUE THREAD

**Issue by Denfenglai** [icqqjs/icqq#52]
### Node.js Version

v18.16.0

### Package(icqq) Version

0.3.14

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

最新版本的协议6也出现了45错误码，换了个号之后也还是一样的情况，删了多次虚拟设备信息
![Screenshot_20230526-111745_EDIT_1685071082169](https://github.com/icqqjs/icqq/assets/129082426/815a4d0b-bb4e-4d77-8ed1-aabdb53ddf30)
都是这种情况，请问有没有解决办法？

### Log Details (控制台日志，请提供包含前后一段时间内的)

![Screenshot_20230526-112224_EDIT_1685071363336](https://github.com/icqqjs/icqq/assets/129082426/764ec5e7-89af-47af-9012-1873e119d68a)

**Comment by citydirector** [comment]
蹲
