### ISSUE TITLE
设置`data_dir`属性后每次登录都会创建新的device文件

### ISSUE THREAD

**Issue by Vi-brance** [icqqjs/icqq#58]
### Node.js Version

18.15.0

### Package(icqq) Version

0.3.15

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

具体问题在这个 [issue](https://github.com/Vi-brance/vscode-qlite/issues/20) 里提及了，在项目中我将`data_dir`设置为一个文件目录，实际使用时控制台总是会输出`创建新的设备文件`

翻阅源码发现模块采用require加载device信息，但是对于完整文件路径似乎无法解析（文件存在的前提成立）

https://github.com/icqqjs/icqq/blob/11da1fbcd644c74727fd27b8d430bee314e3649a/lib/client.ts#L172-L180

频繁更换登录设备似乎更容易出现风控235的问题（issue中提及），算是个恶性bug

建议采用`fs`加载设备文件信息

**Comment by lc-cn** [comment]
已采纳
