### ISSUE TITLE
(45)此协议可能已被禁止登录  使用协议：Android_8.9.50.10650

### ISSUE THREAD

**Issue by ReiiTeaStudio** [icqqjs/icqq#63]
### Node.js Version

使用协议：Android_8.9.50.10650 [2023-06-19T12:53:07.883] [MARK] [icqq] - 182.50.8.188:8080 connected [2023-06-19T12:53:08.070] [ERROR] [icqq] - (45)此协议可能已被禁止登录，建议更换Android_8.8.88（platform: 6）协议后再尝试登录！

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://github.com/icqqjs/icqq/assets/94012185/9be92639-ba7c-4ea0-98af-eb6bf477da1e)
现在8950用不了了吗，用了8.8.88会被冻号

**Comment by K2Lin-Daniel** [comment]
Got frozen too.😥

**Comment by moguixiaolin** [comment]
听他的话，在创建实例的时候传入{platform: 6}，就行了。

**Comment by lc-cn** [comment]
8950登录缺少sign可能会无法登录或无法发送消息，然而这一部分功能需要使用者自行寻找signAPI，配置到0.4.0版本的icqq中，具体配置可群里咨询或自行查看源码
