### ISSUE TITLE
如何实现本地签名组包api

### ISSUE THREAD

**Issue by Xcating** [icqqjs/icqq#65]
如题，如何实现**本地**签名组包api

**Comment by mengxiaoht** [comment]
在线等

**Comment by lc-cn** [comment]
签名api非开源项目

**Comment by mengxiaoht** [comment]
> 签名api非开源项目

哦豁，寄寄了。等別人出了

**Comment by lc-cn** [comment]
解决并发问题后，可能会以api形式免费提供

**Comment by mengxiaoht** [comment]
> 

期待......

**Comment by lc-cn** [comment]
功能已完成，具体细则可在群里提问，群链接见首页README.md

**Comment by Xcating** [comment]
QQ群组搜不到

**Comment by lc-cn** [comment]
[Github]Xcating commented on issue icqqjs/icqq#65
QQ群组搜不到

**Comment by mengxiaoht** [comment]
> 

直接点readme里的邀请链接

**Comment by Xcating** [comment]
NTQQ点不了（

**Comment by mengxiaoht** [comment]
> NTQQ点不了（

手机呢？

**Comment by YM-G9981** [comment]
群满员了，请问还有没有其他群呀

**Comment by lc-cn** [comment]
> 群满员了，请问还有没有其他群呀

已升级群

**Comment by liuzj288** [comment]
> > 群满员了，请问还有没有其他群呀
> 
> 已升级群

群搜不到呢

**Comment by Frodo20** [comment]
点击group，显示管理员已拒绝您的加群申请

**Comment by Frodo20** [comment]
群号是860669870吗？搜不到诶

**Comment by Frodo20** [comment]
能给个进群方法吗？

**Comment by Frodo20** [comment]
> 已经进去了🥵

可以给一个进群方法吗谢谢🙏！

**Comment by pkoukk** [comment]
开源的签名项目，不知道能不能在icqq使用，没试过
https://github.com/fuqiuluo/unidbg-fetch-qsign

**Comment by simo8102** [comment]
> 开源的签名项目，不知道能不能在icqq使用，没试过 https://github.com/fuqiuluo/unidbg-fetch-qsign

测试了下 这个项目可用

**Comment by linonetwo** [comment]
@simo8102 docker 启动后，icqq签名地址直接填localhost端口号就好了吗？这么方便的啊

**Comment by simo8102** [comment]
> @simo8102 docker 启动后，icqq签名地址直接填localhost端口号就好了吗？这么方便的啊

http://127.0.0.1:8080/sign特简单方便  还比较安全点 主动权在自己手上

**Comment by linonetwo** [comment]
懒得搞了， yize 的那个也可以用
