### ISSUE TITLE
Android8.8.8.8协议登录失败

### ISSUE THREAD

**Issue by Xcating** [icqqjs/icqq#70]
### Node.js Version

18.12.1

### Package(icqq) Version

latest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

昨晚很多使用**Android8.8.8.8**协议的机器人都掉线了，提示
![image](https://github.com/icqqjs/icqq/assets/82816129/a6d0a1d1-9c71-45d6-a8c7-2033734dfee2)
_**尝试重新登录显示**_
![image](https://github.com/icqqjs/icqq/assets/82816129/75af9669-b39a-4f58-ab45-7011ae6b55e1)
版本过低，而且无法登录，错误码Code45
其他协议也**无法登录**
---
![image](https://github.com/icqqjs/icqq/assets/82816129/cbac0803-cfeb-4cd3-89ce-c14be45fab59)
看到这位大佬说可以用8.9.58，请问怎么icqq修改并使用8.9.58上线机器人

### Log Details (控制台日志，请提供包含前后一段时间内的)

![image](https://github.com/icqqjs/icqq/assets/82816129/da280f8a-9932-4929-b189-3825364d5d43)
![image](https://github.com/icqqjs/icqq/assets/82816129/267a0201-42e5-4540-9550-27b1f2f4a7ea)

**Comment by yehuankun** [comment]
同样报错怎么解决呢

**Comment by Strawxiguan** [comment]
> 同样报错怎么解决呢

换号或者等更新。没辙，因为你手机QQ也会无法登录

**Comment by Xcating** [comment]
？手机QQ能登录啊

**Comment by Xcating** [comment]
(最新版本)

**Comment by Strawxiguan** [comment]
> (最新版本)
你试试下个8.8的QQ登陆一下试试，大概率是禁止登录
先删除虚拟设备和token，重新登录。
如果code45用手表，等更新。
而且最近不建议上云崽玩了，我号连着一周被冻结两次。
8.8掉线的话，昨晚上一定是tx扫荡了

**Comment by Strawxiguan** [comment]
> (最新版本)

你试试下个8.8的QQ登陆一下试试，大概率是禁止登录
先删除虚拟设备和token，重新登录。
如果code45用手表，等更新。
而且最近不建议上云崽玩了，我号连着一周被冻结两次。
8.8掉线的话，昨晚上一定是tx扫荡了

**Comment by Strawxiguan** [comment]
我今天机器人一个没开，避一下风头

**Comment by Strawxiguan** [comment]
> (最新版本)

拿你的机器人号登录官方手机的QQ，能登上？

**Comment by Xcating** [comment]
能啊

**Comment by Xcating** [comment]
手机和电脑都能登上去

**Comment by Xcating** [comment]
![image](https://github.com/icqqjs/icqq/assets/82816129/d7dda32e-bcc3-40af-a8f6-fced681a8d37)
![image](https://github.com/icqqjs/icqq/assets/82816129/50e31d4b-b1b6-4a9f-bfe4-5eaa258df52d)
删过device和token了

**Comment by Strawxiguan** [comment]
> ![image](https://user-images.githubusercontent.com/82816129/248157669-d7dda32e-bcc3-40af-a8f6-fced681a8d37.png) ![image](https://user-images.githubusercontent.com/82816129/248157673-50e31d4b-b1b6-4a9f-bfe4-5eaa258df52d.png) 删过device和token了

换号或者用手表吧，没救。
有的号现在连那个官方QQ都没法登录

**Comment by hasaki321** [comment]
我的也是相同问题，官方qq能上但是云崽不行

**Comment by ayakasuki** [comment]
手表协议能上但是-70 -80

**Comment by hasaki321** [comment]
手表只能扫码，我服务器和我手机不在一个地区，ip不一样，不能手表协议上

**Comment by YM-G9981** [comment]
> 

VPN穿进去

**Comment by Xcating** [comment]
Tim协议到账，已解除
