### ISSUE TITLE
TIM3.5.1报45

### ISSUE THREAD

**Issue by L1Xu4n** [icqqjs/icqq#75]
今天下午18时bot掉线，凌晨零点尝试修复使用8.88报45，更新后使用TIM同样45
![Screenshot_2023-06-24-00-18-40-010_com microsoft rdc androidx](https://github.com/icqqjs/icqq/assets/106089276/53eab7da-f053-4aff-bb8c-de97aa0cefc5)

**Comment by error46666** [comment]
需要配置签名API

**Comment by L1Xu4n** [comment]
> 需要配置签名API

请问有教程吗?在release没有找到

**Comment by FurryKamenomi** [comment]
> > 需要配置签名API
> 
> 请问有教程吗?在release没有找到

可以寻找有该API的运行商或者icqq的开发者

**Comment by TheTychoStar** [comment]
> > > 需要配置签名API
> > 
> > 
> > 请问有教程吗?在release没有找到
> 
> 可以寻找有该API的运行商或者icqq的开发者

能具体说说如何配置吗，这里好像没找到配置说明。icqq开发者是这个repo的作者吗？要怎么联系？是要购买吗？

**Comment by nilfunc** [comment]
同问，怎么配置API

**Comment by L1Xu4n** [comment]
@nilfunc @TheTychoStar 在readme.md找加群按钮进群找管理要api即可

**Comment by linonetwo** [comment]
@L1Xu4n 是需要购买吗
