### ISSUE TITLE
tim也被封 還有什麼能用

### ISSUE THREAD

**Issue by yidweahzaimen** [icqqjs/icqq#80]
### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

[YzBot][00:04:09.243][MARK] Yunzai-Bot 启动中...
[YzBot][00:04:09.244][MARK] 连接redis....
[YzBot][00:04:09.253][MARK] 连接redis成功
[YzBot][00:04:09.259][MARK] ----------
[YzBot][00:04:09.260][MARK] Package Version: icqq@0.4.7 (Released on 2023/6/25)
[YzBot][00:04:09.260][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
[YzBot][00:04:09.260][MARK] ----------
[YzBot][00:04:09.306][INFO] [3178448067]使用协议：Tim_3.5.1.3168
[YzBot][00:04:09.592][MARK] 43.135.106.161:8080 connected
[YzBot][00:04:09.763][ERRO] 账号被冻结
[YzBot][00:04:09.763][ERRO] 账号已被冻结，已停止运行

C:\yun\Miao-Yunzai\Yunzai-Bot>

![QQ图片20230629001609](https://github.com/icqqjs/icqq/assets/1342053/a30ce020-f8ec-47c6-bcb3-3c057d292dbc)

### Log Details (控制台日志，请提供包含前后一段时间内的)

![QQ图片20230629001609](https://github.com/icqqjs/icqq/assets/1342053/a30ce020-f8ec-47c6-bcb3-3c057d292dbc)

**Comment by ziyuCat** [comment]
冻结了需要解冻，不然什么协议来了都不好使。
