### ISSUE TITLE
签名Api异常

### ISSUE THREAD

**Issue by Aaron001129** [icqqjs/icqq#83]
### Node.js Version

18.15.0

### Package(icqq) Version

0.4.8

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://github.com/icqqjs/icqq/assets/138541637/91ceca8a-66ce-4902-bb2d-b675a8c022f0)
0.4.7不会报错但是上不去，0.4.8报错。

**Comment by lc-cn** [comment]
非icqq的问题，请联系对应签名API提供者。
