### ISSUE TITLE
API的注册等URL问题

### ISSUE THREAD

**Issue by GOOD-AN** [icqqjs/icqq#97]
### Node.js Version

v18.16.0

### Package(icqq) Version

0.4.10

### Login Protocol

aPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

目前个人使用反代来处理请求，希望所有请求都走`https://domain.host/qsign`，比如`https://domain.host/qsign/sign`、`https://domain.host/qsign/register`等等。

而目前的代码使用的是类似`url.pathname = '/register'`这样的形式，会导致除了`sign`以外的其他实际请求变为`https://domain.host/register`。

这样的情况应该如何处理呢？

**Comment by FurryKamenomi** [comment]
but, `url.pathname = '/register'` 等同于 `http(s)://domain/register` 喔。  
See: [!img](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL/mdn-url-all.png)

**Comment by GOOD-AN** [comment]
> but, `url.pathname = '/register'` 等同于 `http(s)://domain/register` 喔。 See: [!img](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL/mdn-url-all.png)

我知道，佬可能没有理解我的意思，我是说如果签名API为`https://domain.host/qsign/sign`，那么我希望`register`是`https://domain.host/qsign/register`，而不是`https://domain.host/register`

我想请教一个良好的解决方案

**Comment by lc-cn** [comment]
v0.4.10以修复

**Comment by GOOD-AN** [comment]
感谢大佬
