### ISSUE TITLE
默默的问下 有获取个性签名的功能吗

### ISSUE THREAD

**Issue by YuNingOvo** [icqqjs/icqq#98]
### Login Protocol

None

**Comment by FurryKamenomi** [comment]
well，设置个性签名setSign走的是sendUni这一块，如果你可以的话，可以试试获取个性签名弄出来

**Comment by FurryKamenomi** [comment]
webapi see github.com/icqqjs/icqq/web-api.md

**Comment by lc-cn** [comment]
将在下一个版本实现，急用可参考[commit](https://github.com/icqqjs/icqq/commit/39be3f5ad3129478f5a56b1bad5582a69bac6c4d)

**Comment by YuNingOvo** [comment]
![image](https://github.com/icqqjs/icqq/assets/31461209/144568ef-7418-4870-89f2-a43a69702ab7)
![image](https://github.com/icqqjs/icqq/assets/31461209/80a9c7ec-d202-4c37-8ce0-d287499fdb7b)
